### ISSUE TITLE
header disappeared on adding plugin

### ISSUE THREAD

**Issue by AnirudhG07** [DreamMaoMao/git-status.yazi#1]
I git cloned the repo and added this in the init.lua
```lua
require("git-status"):setup({
	style = "linemode", -- beside or linemode
})
```
My header disappeared -
<img width="1416" alt="image" src="https://github.com/DreamMaoMao/git-status.yazi/assets/146579014/2a8171ce-c7d9-4de3-9777-d21e3d80576b">

The only reason I am able to think, is I have some TIPS header add ons in my [init.lua](https://github.com/AnirudhG07/dotfiles/blob/stow/yazi/.config/yazi/init.lua). They might be clashing? Please check and tell.(I have not pushed git-status.yazi yet in the repo)

**Comment by DreamMaoMao** [comment]
could you show me the log?

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/git-status.yazi/assets/30348075/d5b02e65-36b9-4ac7-bd7c-2622ef198f16)

This function conflicts with the plugin function

**Comment by AnirudhG07** [comment]
yazi v0.2.5

<img width="740" alt="image" src="https://github.com/DreamMaoMao/git-status.yazi/assets/146579014/2683b7a3-8251-492c-b655-dda5e42759e1">

**Comment by DreamMaoMao** [comment]
i konw what happend to you ,  your yazi is too old, this plugin now follow the lastest yazi-git.

**Comment by AnirudhG07** [comment]
Thanks! it works now. By the way how do you upgrade your yazi without new release (unless building from source code from repo.)

**Comment by DreamMaoMao** [comment]
i always build from souce

**Comment by AnirudhG07** [comment]
Very Very cool. I have so much to learn!!!!
