### ISSUE TITLE
can't show diractory and git branch

### ISSUE THREAD

**Issue by Kicamon** [DreamMaoMao/git-status.yazi#2]
![2024-07-05_01-13](https://github.com/DreamMaoMao/git-status.yazi/assets/96783720/65eb2229-103f-4bd5-894d-038c63af1f42)

**Comment by DreamMaoMao** [comment]
oh  your yazi is too old.  maybe you need to wait the yazi 0.30 release.

**Comment by DreamMaoMao** [comment]
same issue with:
https://github.com/DreamMaoMao/git-status.yazi/issues/1

**Comment by DreamMaoMao** [comment]
You can update yazi to the latest commit or 
remove this code:
![image](https://github.com/DreamMaoMao/git-status.yazi/assets/30348075/3477cb92-1029-4a6b-9f8a-f8e0222c6e06)

**Comment by Kicamon** [comment]
okkkk, thank you~
